In [1]:
import numpy as np
array=np.arange(12)
print("Original array:",array)
reshaped_array=array.reshape((3,4))
print("Reshaped to 3x4:\n",reshaped_array)
reshaped_array_3d=array.reshape((2,3,2))
print("Reshaped to 2x3x2:\n",reshaped_array_3d)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x3x2:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
